### ISSUE TITLE
Laravel 9 support?

### ISSUE THREAD

**Issue by ankurk91** [wimski/laravel-ide-helper-hook-eloquent-has-by-non-dependent-subquery#1]
Laravel 9 will release today.

**Comment by wimski** [comment]
I'm looking into it, although I'm currently facing a package conflict: https://github.com/composer/composer/issues/10528.

**Comment by wimski** [comment]
@ankurk91 this ought to do it:

https://github.com/wimski/laravel-ide-helper-hook-eloquent-has-by-non-dependent-subquery/releases/tag/2.1.0

**Comment by ankurk91** [comment]
Thanks
